version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: lab05_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5434:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

  vuln-api:
    build:
      context: ./vuln-api
    container_name: lab05_vuln_api
    environment:
      NODE_ENV: development
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: app_db
      PORT: 3000
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: unless-stopped

  secure-api:
    build:
      context: ./secure-api
    container_name: lab05_secure_api
    environment:
      NODE_ENV: production
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: app_db
      PORT: 3001
    depends_on:
      - db
    ports:
      - "3001:3001"
    restart: unless-stopped